# include("PermutationGroups/PermutationTest.jl")
# include("PermutationGroups/OrbitTransversalSchreierTest.jl")
# include("PermutationGroups/SchreierSimsTest.jl")
# include("PermutationGroups/TransversalTest.jl")
# include("PermutationGroups/BacktrackTest.jl")
# include("Algorithms/UnionFindTest.jl")
# include("Cohomology/ExactMatricesTest.jl")
# include("PermutationGroups/GroupTest.jl")
# include("SmallPermutationGroupsTest.jl")
# include("FreeGroups/AlphabetsTest.jl")
# include("Experimenting/ResidueTest.jl")
# include("Cohomology/CohomologyTest.jl")
# include("Algorithms/MachineLearning.jl/CNNTest.jl")
# include("FreeGroups/WordTest.jl")
# include("FreeGroups/OrderingTest.jl")
# include("FreeGroups/FreeGroupAutomorphismTest.jl")
include("FreeGroups/WhiteheadAutomorphismsTest.jl")
# include("FreeGroups/WhiteheadAlgorithmTest.jl")